services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=https://vigilant-fortnight-5g56wpx64w6w37xg4-3000.app.github.dev
      - DATABASE_URL=postgresql://neondb_owner:npg_flItXS30KnaU@ep-holy-butterfly-aeg5gfmb-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_YWxlcnQtY2FyaWJvdS03MS5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_i8xJCSTUGaOUrKdw3cTIrDWGRO2eSUp9XUbXQ9ove4
      - CLERK_PUBLISHABLE_KEY=pk_test_YWxlcnQtY2FyaWJvdS03MS5jbGVyay5hY2NvdW50cy5kZXYk
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
